### PR TITLE
Do we want to mention this fringe use case that I have?

### PR DESCRIPTION
**Pull request by griwes**
I'm not sure whether we want to raise this point, because I'm not sure how the committee will react to that (where possibilities might include some members of EWG trying to dismiss the entire paper). Thoughts, @atomgalaxy?

### CODE REVIEW

**Comment by griwes** [comment]
If we don't want to mention this, then I think the paper in its current form is good enough for an r0 for EWG. Either way, @tcbrindle you should request a paper number the way it is described [here](https://isocpp.org/std/standing-documents/sd-7-mailing-procedures-and-how-to-write-papers), so that the paper can be sent once we agree whether we want this change or not.

Bottom line: this is probably ready with or without this PR and some formal steps should be taken to get this to be discussed in Toronto.

**Comment by tcbrindle** [comment]
I've received an official document number, P0665R0, and updated the repo to use it (with a D right now, as it's currently a draft, per [the recommendations](https://isocpp.org/std/standing-documents/sd-7-mailing-procedures-and-how-to-write-papers)).

As to the PR, if I understand correctly you want to be able to do something like

```cpp
namespace ns {
#include "header.hpp"
}
```

where `header.hpp` includes a `std::hash` specialisation? That's kind of nasty IMO, but I can see why it might be useful in some circumstances. Personally I think it might be better to leave it out (because as you say, there's a risk committee members will go "eww" and choose to reject the paper entirely for that reason), but as I won't be in Toronto I'll leave it to you guys to decide whether you want to mention it or not :-).

**Comment by griwes** [comment]
Okay, let's leave it out. Please make sure to send the paper as described in SD-7, before the deadline, which seems to be tomorrow, June 19, at 2pm UTC.

**Comment by tcbrindle** [comment]
Okay, thanks, I'll send it off tonight. Do you have any recommendations for converting Markdown to well-formatted HTML or PDF for submission?

**Pull request closed without merging**
